export const CAMPAIGNS_BREAKDOWN_LOAD_REQUEST = 'CAMPAIGNS_BREAKDOWN_LOAD_REQUEST';
export const CAMPAIGNS_BREAKDOWN_LOAD_SUCCESS = 'CAMPAIGNS_BREAKDOWN_LOAD_SUCCESS';
export const CAMPAIGNS_BREAKDOWN_LOAD_FAILS = 'CAMPAIGNS_BREAKDOWN_LOAD_FAILS';

export const CAMPAIGNS_DOWNLOAD_REPORT_REQUEST = 'CAMPAIGNS_DOWNLOAD_REPORT_REQUEST';
export const CAMPAIGNS_DOWNLOAD_REPORT_SUCCESS = 'CAMPAIGNS_DOWNLOAD_REPORT_SUCCESS';
export const CAMPAIGNS_DOWNLOAD_REPORT_FAIL = 'CAMPAIGNS_DOWNLOAD_REPORT_FAIL';
