export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';
export const PROFILE_LOAD_FAIL = 'PROFILE_LOAD_FAIL';
export const RESET_PROFILE_STATE = 'RESET_PROFILE_STATE';
