export const TEAM_MEMBERS_BREAKDOWN_LOAD_REQUEST = 'TEAM_MEMBERS_BREAKDOWN_LOAD_REQUEST';
export const TEAM_MEMBERS_BREAKDOWN_LOAD_SUCCESS = 'TEAM_MEMBERS_BREAKDOWN_LOAD_SUCCESS';
export const TEAM_MEMBERS_BREAKDOWN_LOAD_FAILS = 'TEAM_MEMBERS_BREAKDOWN_LOAD_FAILS';

export const TEAM_MEMBERS_DOWNLOAD_REPORT_REQUEST = 'TEAM_MEMBERS_DOWNLOAD_REPORT_REQUEST';
export const TEAM_MEMBERS_DOWNLOAD_REPORT_SUCCESS = 'TEAM_MEMBERS_DOWNLOAD_REPORT_SUCCESS';
export const TEAM_MEMBERS_DOWNLOAD_REPORT_FAIL = 'TEAM_MEMBERS_DOWNLOAD_REPORT_FAIL';
