export const OVERVIEW_LOAD_REQUEST = 'OVERVIEW_LOAD_REQUEST';
export const OVERVIEW_LOAD_SUCCESS = 'OVERVIEW_LOAD_SUCCESS';
export const OVERVIEW_LOAD_FAIL = 'OVERVIEW_LOAD_FAIL';

export const OVERVIEW_DOWNLOAD_REPORT_REQUEST = 'OVERVIEW_DOWNLOAD_REPORT_REQUEST';
export const OVERVIEW_DOWNLOAD_REPORT_SUCCESS = 'OVERVIEW_DOWNLOAD_REPORT_SUCCESS';
export const OVERVIEW_DOWNLOAD_REPORT_FAIL = 'OVERVIEW_DOWNLOAD_REPORT_FAIL';
