export const CONTACTS_BREAKDOWN_LOAD_REQUEST = 'CONTACTS_BREAKDOWN_LOAD_REQUEST';
export const CONTACTS_BREAKDOWN_LOAD_SUCCESS = 'CONTACTS_BREAKDOWN_LOAD_SUCCESS';
export const CONTACTS_BREAKDOWN_LOAD_FAILS = 'CONTACTS_BREAKDOWN_LOAD_FAILS';

export const CONTACTS_DOWNLOAD_REPORT_REQUEST = 'CONTACTS_DOWNLOAD_REPORT_REQUEST';
export const CONTACTS_DOWNLOAD_REPORT_SUCCESS = 'CONTACTS_DOWNLOAD_REPORT_SUCCESS';
export const CONTACTS_DOWNLOAD_REPORT_FAIL = 'CONTACTS_DOWNLOAD_REPORT_FAIL';
