import { IGiftInvitesCampaignSettings } from '../giftInvites.types';

export const giftInvitesCampaignSettingsMock: IGiftInvitesCampaignSettings = {
  can_override_gift_default_budget: true,
  can_override_recipient_video: true,
  can_override_required_actions: 1,
  countryIds: [2],
  customisation: {
    recipient_video: 'string',
    recipient_video_type: 'string',
    redirect_button: 'string',
    redirect_confirm: true,
    redirect_header: 'string',
    redirect_message: 'string',
    redirect_url: 'string',
    vidyard_image: 'string',
    vidyard_video: 'string',
  },
  defaultProductId: 2,
  disabled_gift_invitation_method_ids: [],
  enterprise_min_price: 100,
  enterprise_max_price: 200,
  enterprise_donation_price: 200,
  enterprise_gift_card_price: 200,
  gift_default_budget: null,
  gift_expiration: 90,
  gift_limits_count: 10,
  gift_limits_period: 'week',
  productIsSuitable: true,
  required_actions: {
    capture_affidavit: false,
    capture_date: false,
    capture_email: false,
    capture_phone: false,
    capture_question: false,
    gifter_affidavit: 'string',
    gifter_question: 'string',
  },
  restricted_product_ids: [],
  vendor: 'vendor',
};
