export const TEAMS_BREAKDOWN_LOAD_REQUEST = 'TEAMS_BREAKDOWN_LOAD_REQUEST';
export const TEAMS_BREAKDOWN_LOAD_SUCCESS = 'TEAMS_BREAKDOWN_LOAD_SUCCESS';
export const TEAMS_BREAKDOWN_LOAD_FAILS = 'TEAMS_BREAKDOWN_LOAD_FAILS';

export const TEAMS_DOWNLOAD_REPORT_REQUEST = 'TEAMS_DOWNLOAD_REPORT_REQUEST';
export const TEAMS_DOWNLOAD_REPORT_SUCCESS = 'TEAMS_DOWNLOAD_REPORT_SUCCESS';
export const TEAMS_DOWNLOAD_REPORT_FAIL = 'TEAMS_DOWNLOAD_REPORT_FAIL';
